# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - gofmt
    - misspell
    - unparam
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - nakedret
    - nolintlint
    - whitespace
  disable:
    - unused
    - gosec
    - unconvert
    - prealloc
    - staticcheck
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    disable-all: false
    enable:
      - shadow
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: absensholat-api
  
  misspell:
    locale: US
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
  
  gosec:
    excludes:
      - G104
  
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-dirs:
    - docs
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    
    - path: docs/
      linters:
        - all
    
    - linters:
        - lll
      source: "^//\\s+@"

  max-issues-per-linter: 50
  max-same-issues: 10
